/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:dcef811d-cbf5-4ebe-9717-40c74bb942a7",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_W5ZWMefoo",
    "aws_user_pools_web_client_id": "1gm3nlim70k3uj0en8gpip97gj",
    "oauth": {}
};


export default awsmobile;
